-- Generated by Horizons custom animations editor
-- Preset: Smooth (default) - Material Design "standard" easing family:
-- balanced, everyday motion that neither rushes nor lingers. Good default
-- for daily driving; angle animations (border/shadow/glow gradient spin)
-- stay off since they're a decorative flourish, not part of the base feel.
hl.curve("sm_standard", { type = "bezier", points = { {0.4, 0},   {0.2, 1}   } }) -- Material standard
hl.curve("sm_decel",    { type = "bezier", points = { {0,   0},   {0.2, 1}   } }) -- Material standard decelerate
hl.curve("sm_accel",    { type = "bezier", points = { {0.4, 0},   {1,   1}   } }) -- Material standard accelerate
hl.curve("sm_linear",   { type = "bezier", points = { {0,   0},   {1,   1}   } }) -- for continuous angle loops
hl.animation({ leaf = "global",              enabled = true,  speed = 10,  bezier = "sm_standard"                    })
hl.animation({ leaf = "windows",             enabled = true,  speed = 4.2, bezier = "sm_standard"                    })
hl.animation({ leaf = "windowsIn",           enabled = true,  speed = 3.6, bezier = "sm_decel",  style = "popin 85%" })
hl.animation({ leaf = "windowsOut",          enabled = true,  speed = 2.6, bezier = "sm_accel",  style = "popin 85%" })
hl.animation({ leaf = "windowsMove",         enabled = true,  speed = 4,   bezier = "sm_standard"                    })
hl.animation({ leaf = "layers",              enabled = true,  speed = 3,   bezier = "sm_standard"                    })
hl.animation({ leaf = "layersIn",            enabled = true,  speed = 3,   bezier = "sm_decel",  style = "slide"     })
hl.animation({ leaf = "layersOut",           enabled = true,  speed = 2.4, bezier = "sm_accel",  style = "slide"     })
hl.animation({ leaf = "fade",                enabled = true,  speed = 3,   bezier = "sm_standard"                    })
hl.animation({ leaf = "fadeIn",              enabled = true,  speed = 3,   bezier = "sm_decel"                       })
hl.animation({ leaf = "fadeOut",             enabled = true,  speed = 2.4, bezier = "sm_accel"                       })
hl.animation({ leaf = "fadeSwitch",          enabled = true,  speed = 2,   bezier = "sm_standard"                    })
hl.animation({ leaf = "fadeShadow",          enabled = true,  speed = 3,   bezier = "sm_standard"                    })
hl.animation({ leaf = "fadeDim",             enabled = true,  speed = 3,   bezier = "sm_standard"                    })
hl.animation({ leaf = "fadeLayersIn",        enabled = true,  speed = 2.6, bezier = "sm_decel"                       })
hl.animation({ leaf = "fadeLayersOut",       enabled = true,  speed = 2.2, bezier = "sm_accel"                       })
hl.animation({ leaf = "fadePopups",          enabled = true,  speed = 2.4, bezier = "sm_standard"                    })
hl.animation({ leaf = "fadePopupsIn",        enabled = true,  speed = 2.4, bezier = "sm_decel"                       })
hl.animation({ leaf = "fadePopupsOut",       enabled = true,  speed = 2,   bezier = "sm_accel"                       })
hl.animation({ leaf = "fadeDpms",            enabled = true,  speed = 6,   bezier = "sm_standard"                    })
hl.animation({ leaf = "border",              enabled = true,  speed = 6,   bezier = "sm_standard"                    })
hl.animation({ leaf = "borderangle",         enabled = false, speed = 30,  bezier = "sm_linear", style = "loop"      })
hl.animation({ leaf = "shadowangle",         enabled = false, speed = 30,  bezier = "sm_linear", style = "loop"      })
hl.animation({ leaf = "glowangle",           enabled = false, speed = 30,  bezier = "sm_linear", style = "loop"      })
hl.animation({ leaf = "workspaces",          enabled = true,  speed = 5,   bezier = "sm_standard", style = "slide"   })
hl.animation({ leaf = "workspacesIn",        enabled = true,  speed = 4.5, bezier = "sm_decel",  style = "slide"     })
hl.animation({ leaf = "workspacesOut",       enabled = true,  speed = 3.6, bezier = "sm_accel",  style = "slide"     })
hl.animation({ leaf = "specialWorkspace",    enabled = true,  speed = 4,   bezier = "sm_standard", style = "slidevert" })
hl.animation({ leaf = "specialWorkspaceIn",  enabled = true,  speed = 4,   bezier = "sm_decel",  style = "slidevert" })
hl.animation({ leaf = "specialWorkspaceOut", enabled = true,  speed = 3,   bezier = "sm_accel",  style = "slidevert" })
hl.animation({ leaf = "zoomFactor",          enabled = true,  speed = 6,   bezier = "sm_standard"                    })
