#!/usr/bin/env bash
# Apply cursor theme + size. Usage: set-cursor-theme.sh <theme> [size]
# Niri's own cursor is handled separately via qssettings/shell.kdl.
set -u

theme="$1"
size="${2:-24}"
[[ -z "$theme" ]] && { echo "usage: $0 <cursor-theme> [size]" >&2; exit 1; }

gsettings set org.gnome.desktop.interface cursor-theme "$theme" 2>/dev/null
gsettings set org.gnome.desktop.interface cursor-size "$size" 2>/dev/null

# New processes need the same values even if they do not use gsettings
# directly (many Qt, SDL and terminal apps look only at XCURSOR_*).
mkdir -p "$HOME/.config/environment.d"
cat >"$HOME/.config/environment.d/90-horizons-cursor.conf" <<EOF
XCURSOR_THEME=$theme
XCURSOR_SIZE=$size
EOF

# Default cursor inheritance for X11/legacy apps
mkdir -p "$HOME/.icons/default"
cat >"$HOME/.icons/default/index.theme" <<EOF
[Icon Theme]
Name=Default
Comment=Default cursor theme (generated by shell settings)
Inherits=$theme
EOF

# xsettingsd covers X11/XWayland clients which do not read the GTK settings.
XSETTINGSD_CONFIG="$HOME/.config/xsettingsd/xsettingsd.conf"
mkdir -p "$(dirname "$XSETTINGSD_CONFIG")"
if grep -q '^Gtk/CursorThemeName' "$XSETTINGSD_CONFIG" 2>/dev/null; then
    sed -i "s|^Gtk/CursorThemeName.*|Gtk/CursorThemeName \"$theme\"|" "$XSETTINGSD_CONFIG"
else
    echo "Gtk/CursorThemeName \"$theme\"" >>"$XSETTINGSD_CONFIG"
fi
if grep -q '^Gtk/CursorThemeSize' "$XSETTINGSD_CONFIG" 2>/dev/null; then
    sed -i "s|^Gtk/CursorThemeSize.*|Gtk/CursorThemeSize $size|" "$XSETTINGSD_CONFIG"
else
    echo "Gtk/CursorThemeSize $size" >>"$XSETTINGSD_CONFIG"
fi
pkill -HUP xsettingsd 2>/dev/null || true

# Apply immediately for the current Hyprland session as well; the command is
# absent under other compositors, which is intentionally harmless.
if command -v hyprctl >/dev/null 2>&1; then
    hyprctl setcursor "$theme" "$size" >/dev/null 2>&1 || true
fi

exit 0
